export enum ActionType {
  GET_VIDEOS_LIST = 'GET_VIDEOS_LIST',
  GET_VIDEOS_LIST_LOADING = 'GET_VIDEOS_LIST_LOADING',
  GET_VIDEOS_LIST_ERROR = 'GET_VIDEOS_LIST_ERROR',

  SET_VIDEO_TO_WATCH = 'SET_VIDEO_TO_WATCH',
};